---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-secret-updater
  namespace: ecr-secret-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecr-secret-updater
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-secret-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ecr-secret-updater
subjects:
  - kind: ServiceAccount
    name: ecr-secret-updater
    namespace: ecr-secret-updater
